Repository factoriotools/factorio-docker, pull requests merged in 2019-05, with the labels that each got.

#226 Quote all vars, remove useless echo/sub-shell, add shebands, formatting
  0.14/build.sh
  0.14/clean.sh
  0.14/docker-entrypoint.sh
  0.14/run.sh
  0.15/docker-entrypoint.sh
  0.16/files/docker-entrypoint.sh
  0.16/files/scenario.sh
  0.16/files/scenario2map.sh
  0.17/files/docker-entrypoint.sh
  0.17/files/scenario.sh
  0.17/files/scenario2map.sh
Labels: enhancement

#242 Fixed naming of `$SCENARIOS`
  0.16/files/scenario.sh
  0.16/files/scenario2map.sh
  0.17/files/scenario.sh
  0.17/files/scenario2map.sh
Labels: code quality

#245 Advance CI features
  .travis.yml
  0.17/files/docker-entrypoint.sh
  build.sh
Labels: ci, enhancement

#255 fix for .tmp.zip saves not being deleted on start
  0.17/files/docker-entrypoint.sh
Labels: bug

#259 Quote all vars in Dockerfile
  0.17/Dockerfile
Labels: code quality, enhancement

#256 Allow puid/pgid to be set as environment vars on stable
  0.16/Dockerfile
  0.16/files/docker-entrypoint.sh
Labels: enhancement
